### ISSUE TITLE
Unable to extract

### ISSUE THREAD

**Issue by posix4e** [xwzy/Triplet-deep-hash-pytorch#3]
$ python3 batch_extarct_test.py 
Using TensorFlow backend.
2017-12-07 19:10:43.313193: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
  0%|                                                                                                         | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "batch_extarct_test.py", line 83, in <module>
    f = poolingPreds(predict(model, os.path.join(basePath, i)))
  File "batch_extarct_test.py", line 68, in predict
    img = get_processed_image(path)
  File "batch_extarct_test.py", line 49, in get_processed_image
    im = np.asarray(cv2.imread(img_path))[:, :, ::-1]
IndexError: too many indices for array

**Comment by posix4e** [comment]
Fixed by moving to glob
```
diff --git a/triplet-deep-hash-pytorch/feature/test/test.npy b/triplet-deep-hash-pytorch/feature/test/test.npy
index 9daeafb..8929749 100644
Binary files a/triplet-deep-hash-pytorch/feature/test/test.npy and b/triplet-deep-hash-pytorch/feature/test/test.npy differ
diff --git a/triplet-deep-hash-pytorch/src/extract_feature/batch_extarct_test.py b/triplet-deep-hash-pytorch/src/extract_feature/batch_extarct_test.py
index a3e7452..e321088 100644
--- a/triplet-deep-hash-pytorch/src/extract_feature/batch_extarct_test.py
+++ b/triplet-deep-hash-pytorch/src/extract_feature/batch_extarct_test.py
@@ -5,6 +5,7 @@ import cv2
 import os
 import skimage.measure
 from tqdm import tqdm
+import glob
 
 # This function comes from Google's ImageNet Preprocessing Script
 def central_crop(image, central_fraction):
@@ -46,7 +47,9 @@ def central_crop(image, central_fraction):
 
 def get_processed_image(img_path):
     # Load image and convert from BGR to RGB
-    im = np.asarray(cv2.imread(img_path))[:, :, ::-1]
+    cv_img = cv2.imread(img_path)
+    im = np.asarray(cv_img)
+    im = im[:, :, ::-1]
     im = central_crop(im, 0.875)
     im = cv2.resize(im, (299, 299))
     im = inception_v4.preprocess_input(im)
@@ -72,15 +75,10 @@ def predict(model, path):
 
 if __name__ == "__main__":
     model = inception_v4.create_model(weights='imagenet', include_top=False)
-
-    basePath = '../../data/test/'
-    imageName = os.listdir(basePath)
+    images = glob.glob("../../data/test/*/*.jpg")
     feature_list = np.array([[]])
-    for ii in tqdm(range(len(imageName))):
-        i = imageName[ii]
-        if i.startswith('.'):
-            continue
-        f = poolingPreds(predict(model, os.path.join(basePath, i)))
+    for i in tqdm(images):
+        f = poolingPreds(predict(model, i))
         if feature_list.size == 0:
             feature_list = np.array([f])
         else:
```

**Comment by xwzy** [comment]
Feel free to make a PR.

**Comment by xwzy** [comment]
The original code works on my computer. Maybe `os.listdir()` return some garbage file like `.DS_store` or other.
